Rica carv missing avatar check reopens pull #5241
e107inc/e107 pull request #5311
Opened 2024-08-04 07:55 UTC by rica-carv

### Motivation and Context
External avatar files, when missing, give this output:
![Screenshot 2024-04-27 at 11-37-17 SelosPT](https://github.com/e107inc/e107/assets/17130530/31924944-ea08-4c4b-b35b-2acf136e327f)
![Screenshot 2024-04-27 at 11-36-55 Gestor de plugins - Instalado - Área do administrador SelosPT](https://github.com/e107inc/e107/assets/17130530/40c0c0f2-0d29-46b8-ac94-60fe9359aae1)

### Description
Added code to revert to default avatar image, when external file is missing, output like this:
![Screenshot 2024-04-27 at 12-52-09 SelosPT](https://github.com/e107inc/e107/assets/17130530/ddccfc5b-4bb6-4635-8767-a67586c2476e)
![Screenshot 2024-04-27 at 12-51-40 Língua - Área do administrador SelosPT](https://github.com/e107inc/e107/assets/17130530/2cfb22ce-26a3-4d4b-96f6-f4d84a05e2d0)

### How Has This Been Tested?
Tested in e107 v2.3.3 clean install,
Output tested in admin area and in the front end (pics above)

### Types of Changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist
- [x] My code adheres to the e107 [code style standard](https://github.com/e107inc/e107/wiki/e107-Coding-Standard).
- [ ] I have read the [**contributing** document](https://github.com/e107inc/e107/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/e107inc/e107/tree/master/e107_tests) to cover my changes.
- [ ] All new and existing tests pass.

2026-08-10 19:07 UTC, rica-carv commented
OK, do your best....

2026-08-23 19:49 UTC, Deltik requested changes

2026-08-23 19:49 UTC, Deltik commented on e107_handlers/e_parse_class.php
> +		$text .= '<img ' . $id . "class='" . $class . $classOnline . "' alt=\"" . $title . "\" src='" . $url . "'  width='" . $width . "' " . $heightInsert . $style . $loading . $onError . ' />';
@e107help: Could you assemble this with `\e_parse::toAttributes()`?

2026-08-24 22:08 UTC, Deltik approved these changes

2026-08-24 22:08 UTC, merged